### ISSUE TITLE
Custom css file changes being applied

### ISSUE THREAD

**Issue by hildebrand-institute** [markdownreveal/markdownreveal#49]
Hola, que tal?
Many thanks for your nice work. I was wondering about the opportunity of implementing markdownreveal code for the fallowing reason. A silly issue arises when one has made some changes to his/her custom css file. At least on Debian it is then necessary not only to reboot markdownreveal from a new terminal session, but also to delete browser history, in order to see style changes being reflected within the slides. If someone is not aware of this, chances are that time will be lost for understanding why changes to custom css do not happen to be applied (that was my sad experience ;-( ).

It might be not a great issue to add some lines of code for making this operation automatic...

At least it would be useful to add a warning within markdownreveal documentation.
Thanks!
Alessandro

**Comment by Peque** [comment]
@hildebrand-institute I gues you have your CSS rules in `style/custom.css`, right?

Once you modify that file, it should be updated correctly from Markdown. But your browser will probably cache the style rules.

Can you try this?

- Update the CSS rules
- Do not reboot Markdownreveal
- With your web browser window selected, press <kbd>CTRL</kbd>+<kbd>MAYUS</kbd>+<kbd>R</kbd> (this will force your browser to reload CSS files)

If that works (I think it will), it means simply that your browser is caching the CSS rules. I am not sure if Markdownreveal can force the browser to reload those rules. Otherwise, feel free to add a note in the documentation. :+1: :blush:

**Comment by hildebrand-institute** [comment]
@Peque Your suggestion doesn't seem to work with Chromium. 

I definitely have to reboot Markdownreveal from a new terminal. With ctrl+shift+r I can avoid to manually delete the browser cache, but in any case then a reboot is necessary...

**Comment by Peque** [comment]
Cannot reproduce, sorry. Using Chromium 79.0.3945.88 and Markdownreveal 0.3.4 from Linux (Fedora 31). :woman_shrugging: 

![out](https://user-images.githubusercontent.com/526577/72668455-691f0e80-3a27-11ea-961c-37bdb13ef3f0.gif)

Try updating Markdownreveal and your browser if they are outdated.

Which operating system are you using?

**Comment by hildebrand-institute** [comment]
I'm using Debian Stretch, which is a good OS, except may be exactly when one wants programs' latest versions. As for updating Chromium (here 73.0.3683.75 is installed) I get a lot of problems with the numerous dependencies... So I'll give up for the moment. May be I should give Fedora a try. Thanks, anyway

**Comment by Peque** [comment]
@hildebrand-institute Make sure you have Markdownreveal updated too (0.3.4 is the latest version).
